language: java
jdk:
  - oraclejdk7

before_install:
  - sudo rm -f /etc/mavenrc

install:
  - mvn install -DskipTests -pl kuromoji-ipadic -pl kuromoji-unidic -am

script:
  - mvn test -DskipCompileDictionary -pl kuromoji-ipadic -pl kuromoji-unidic -am

